### ISSUE TITLE
build-on-commit fails for single-series charms

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/layer-cwr#28]
Instead of getting the series from the charm, it assumes that the charm is multi-series if an explicit one isn't given.

```
Started by user admin
Building in workspace /var/lib/jenkins/jobs/charm-hadoop-client/workspace
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/juju-solutions/layer-hadoop-client # timeout=10
Fetching upstream changes from https://github.com/juju-solutions/layer-hadoop-client
 > git --version # timeout=10
 > git fetch --tags --progress https://github.com/juju-solutions/layer-hadoop-client +refs/heads/*:refs/remotes/origin/*
 > git rev-parse refs/remotes/origin/master^{commit} # timeout=10
 > git rev-parse refs/remotes/origin/origin/master^{commit} # timeout=10
Checking out Revision f415894c60b724e3c999ecf5b0dd14b13526a1f3 (refs/remotes/origin/master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f415894c60b724e3c999ecf5b0dd14b13526a1f3
 > git rev-list f415894c60b724e3c999ecf5b0dd14b13526a1f3 # timeout=10
[workspace] $ /bin/bash /tmp/hudson5149885354489927800.sh
+ '[' '!' -f first-run.lock ']'
+ export JUJU_REPOSITORY=/tmp/
+ JUJU_REPOSITORY=/tmp/
+ OUTPUT_DIR=builds
+ SERIES_FLAG=
+ '[' '!' -z '' ']'
+ charm build
build: Composing into /tmp/
build: Destination charm directory: /tmp/trusty/hadoop-client
build: Processing layer: layer:basic
build: Processing layer: hadoop-client
build: Processing interface: hadoop-plugin
build: Processing interface: java
proof: I: relation mahout has no hooks
proof: I: File config.yaml not found.
+ juju switch aws
aws (controller) (no change)
++ juju add-model wont-be-added --credential invalid-credential
++ sed -e 's/.*cloud "\?\([^ "]*\)"\?.*/\1/'
+ cloud=aws
+ credential_arg=
+ [[ aws != \l\o\c\a\l\h\o\s\t ]]
+ [[ aws != \l\x\d ]]
+ juju credentials --format=json
+ grep -q aws
++ juju credentials --format=json
++ jq -r '.credentials.aws."cloud-credentials" | keys[0]'
+ credential=default
+ credential_arg=--credential=default
+ juju add-model test-hadoop-client-2 --credential=default
Uploading credential 'aws/ci2/default' to controller
Added 'test-hadoop-client-2' model on aws/us-east-1 with credential 'default' for user 'ci2'
+ trap cleanup_model EXIT
+ '[' -e /tmp/bundles ']'
+ mkdir /tmp/bundles
+ rm -rf /tmp/bundles/cs_hadoop_processing
+ charm pull cs:hadoop-processing /tmp/bundles/cs_hadoop_processing
cs:bundle/hadoop-processing-39
++ update_bundle
++ cat
+ python3 -c 'import yaml
with open('\''/tmp/bundles/cs_hadoop_processing/bundle.yaml'\'', '\''r'\'') as fp:
    bundle = yaml.safe_load(fp)
app = bundle.get('\''applications'\'', bundle.get('\''services'\'', {}))['\''client'\'']
app['\''charm'\''] = '\''/tmp/builds/hadoop-client'\''
with open('\''/tmp/bundles/cs_hadoop_processing/bundle.yaml'\'', '\''w'\'') as fp:
    yaml.dump(bundle, fp)'
+ rm -f totest.yaml
+ echo 'bundle: /tmp/bundles/cs_hadoop_processing'
+ echo 'bundle_name: hadoop-client_in_cs_hadoop_processing'
+ echo 'bundle_file: bundle.yaml'
+ cwr -F aws:test-hadoop-client-2 totest.yaml --results-dir /srv/artifacts --test-id 2
2017-01-06 20:51:26 INFO Running test on AWS.
2017-01-06 20:51:39 ERROR Exception (aws:test-hadoop-client-2):
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/run.py", line 138, in run_plan
    test_result = self.run_tests(test_plan, env)
  File "/usr/local/lib/python2.7/dist-packages/cloudweatherreport/run.py", line 208, in run_tests
    status = tester.main(self.args)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/tester.py", line 132, in main
    suite = spec.SuiteFactory(options, options.testdir)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 358, in SuiteFactory
    suite.find_suite()
  File "/usr/local/lib/python2.7/dist-packages/bundletester/spec.py", line 206, in find_suite
    model = models.Charm.from_deployer_charm(charm)
  File "/usr/local/lib/python2.7/dist-packages/bundletester/models.py", line 38, in from_deployer_charm
    shutil.copytree(dcharm.path, charm_dir, symlinks=True)
  File "/usr/lib/python2.7/shutil.py", line 171, in copytree
    names = os.listdir(src)
OSError: [Errno 2] No such file or directory: '/tmp/builds/hadoop-client'

+ ln -s /srv/artifacts/hadoop-client_in_cs_hadoop_processing/2 /var/lib/jenkins/jobs/charm-hadoop-client/builds/2/archive
+ '[' '!' -z '' ']'
+ cleanup_model
+ juju destroy-model test-hadoop-client-2 -y
Destroying model
Waiting on model to be removed...
Waiting on model to be removed...
Finished: SUCCESS
```

**Comment by johnsca** [comment]
Actually, we shouldn't even care about the series, since it should be controller by the reference bundle.

**Comment by johnsca** [comment]
It turns out that we have to force the series into the path because deployer prefers that over the default series in the bundle.  Closing this for now.
