### ISSUE TITLE
Bundle proof chokes on local charm

### ISSUE THREAD

**Issue by johnsca** [juju-solutions/layer-cwr#34]
```
Traceback (most recent call last):
  File "/usr/bin/charm-proof", line 9, in <module>
    load_entry_point('charm-tools==2.1.9', 'console_scripts', 'charm-proof')()
  File "/usr/lib/python2.7/dist-packages/charmtools/proof.py", line 63, in main
    lint, exit_code = proof(args_.charm_name, args_.bundle, args_.debug)
  File "/usr/lib/python2.7/dist-packages/charmtools/proof.py", line 57, in proof
    lint, err_code = c.proof()
  File "/usr/lib/python2.7/dist-packages/charmtools/bundles.py", line 92, in proof
    lint.proof(self)
  File "/usr/lib/python2.7/dist-packages/charmtools/bundles.py", line 47, in proof
    errors = jujubundlelib.validation.validate(data)
  File "/usr/lib/python2.7/dist-packages/jujubundlelib/validation.py", line 52, in validate
    _validate_services(services, machines, add_error)
  File "/usr/lib/python2.7/dist-packages/jujubundlelib/validation.py", line 151, in _validate_services
    placement, services, machines, charm, add_error)
  File "/usr/lib/python2.7/dist-packages/jujubundlelib/validation.py", line 368, in _validate_placement
    if charm.series and series and charm.series != series:
AttributeError: 'NoneType' object has no attribute 'series'
```

We're hitting this with the CWR charm because of the bundle munging.  Not sure if this needs to be fixed in the charm somehow or in jujubundlelib.  Certainly, we would expect proof to fail (or at least WARN) a bundle with local charms instead of erroring.

**Comment by kwmonroe** [comment]
I'm not able to repro this with cwr rev 44.  Is this still a valid issue @johnsca, or was it fixed when we started proofing the `bundle.yaml` whilst running the `bundle-cwr.yaml` (#42)?

**Comment by johnsca** [comment]
That PR should have fixed this, yes.
