### ISSUE TITLE
error with charm push in the build-bundle action

### ISSUE THREAD

**Issue by kwmonroe** [juju-solutions/layer-cwr#50]
When I register a bundle with the build-bundle action, I get this:

```
Testing new bundle
Running cwr -F --results-dir /srv/artifacts --test-id 1 localhost:test-java-devenv-1 totest.yaml
2017-02-01 18:55:16 INFO Running test on lxd.
2017-02-01 19:29:31 INFO Starting new HTTP connection (1): svg.juju.solutions
Releasing bundle
Running charm push /tmp/tmph_6nq8rh cs:~kwmonroe/java-devenv --channel beta
error: flag provided but not defined: --channel
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-cwr-0/charm/scripts/bundlebuilder.py", line 454, in <module>
    tester.test_and_release_bundle(repo, branch, build_num, models)
  File "/var/lib/juju/agents/unit-cwr-0/charm/scripts/bundlebuilder.py", line 421, in test_and_release_bundle
    bundle.release()
  File "/var/lib/juju/agents/unit-cwr-0/charm/scripts/bundlebuilder.py", line 247, in release
    execute(cmd)
  File "/var/lib/juju/agents/unit-cwr-0/charm/scripts/bundlebuilder.py", line 37, in execute
    raise Exception("Command {} failed with {}".format(" ".join(cmd), p.returncode))
Exception: Command charm push /tmp/tmph_6nq8rh cs:~kwmonroe/java-devenv --channel beta failed with 2
```

It seems the `release()` method is doing a `charm push --channel`, which is an invalid option for `push`:

https://github.com/juju-solutions/layer-cwr/blob/master/scripts/bundlebuilder.py#L245

Instead, I believe it needs to do a `charm push` followed by a `charm release --channel`.

**Comment by kwmonroe** [comment]
FYI, i ran this action to repro this:

```
juju run-action cwr/0 build-bundle repo=https://github.com/kwmonroe/bundle-java-devenv.git branch=master bundle-name=java-devenv controller=localhost
```

And my `ci-info.yaml` lives here:

https://github.com/kwmonroe/bundle-java-devenv/blob/master/ci-info.yaml
